services:
  - type: worker
    name: jazz-store-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
